# common/constants.py

# Trial & subscription
FREE_TRIAL_DAYS = 7
SUBSCRIPTION_REMINDER_DAYS = [3, 2, 1]
MAX_SUBSCRIPTIONS_PER_USER = 20

# Batching
DEFAULT_BATCH_SIZE = 100
NOTIFICATION_BATCH_SIZE = 100

# Scraping
SCRAPER_CUTOFF_MINUTES = 5
MAX_SCRAPER_ADS_PER_RUN = 10

# Bot pool
DEFAULT_MAX_USERS_PER_BOT = 5000

# Maintenance
CLEANUP_DEFAULT_DAYS = 30
ACTIVE_USER_LOOKBACK_DAYS = 7
